[tool.poetry]
name = "210-api"
version = "0.1.0"
description = ""
authors = ["zfenton <zacharytfenton@berkeley.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.115.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
